const COURSES = [
    {
        id: 1,
        tags: ['Программирование', 'JavaScript'],
        name: 'Elderly Mobility Scale',
        yearFrom: '2025',
        yearTo: '2026',
        date: '01.11.2023',
        price: '812',
    },
    {
        id: 2,
        tags: ['Программирование', 'JavaScript', 'Git'],
        name: 'JavaScript Basics',
        yearFrom: '2023',
        yearTo: '2024',
        date: '15.01.2023',
        price: '650',
    },
    {
        id: 3,
        tags: ['Программирование', 'Python'],
        name: 'Intro to Python Programming',
        yearFrom: '2024',
        yearTo: '2025',
        date: '10.02.2024',
        price: '950',
    },
    {
        id: 4,
        tags: ['Программирование', 'C#'],
        name: 'C# for Beginners',
        yearFrom: '2025',
        yearTo: '2026',
        date: '05.03.2025',
        price: '780',
    },
    {
        id: 5,
        tags: ['Программирование', 'Java'],
        name: 'Advanced Java Techniques',
        yearFrom: '2026',
        yearTo: '2027',
        date: '01.04.2026',
        price: '1100',
    },
    {
        id: 6,
        tags: ['Программирование', 'JavaScript', 'Web Development'],
        name: 'Modern JavaScript Frameworks',
        yearFrom: '2024',
        yearTo: '2025',
        date: '20.06.2024',
        price: '1020',
    },
    {
        id: 7,
        tags: ['Программирование', 'C++'],
        name: 'C++ for Advanced Programmers',
        yearFrom: '2023',
        yearTo: '2024',
        date: '25.08.2023',
        price: '950',
    },
    {
        id: 8,
        tags: ['Программирование', 'Data Science'],
        name: 'Data Science Fundamentals',
        yearFrom: '2025',
        yearTo: '2026',
        date: '13.09.2025',
        price: '1300',
    },
    {
        id: 9,
        tags: ['Программирование', 'Web Development', 'HTML/CSS'],
        name: 'HTML & CSS Mastery',
        yearFrom: '2024',
        yearTo: '2025',
        date: '03.10.2024',
        price: '560',
    },
    {
        id: 10,
        tags: ['Программирование', 'Ruby'],
        name: 'Mastering Ruby Programming',
        yearFrom: '2023',
        yearTo: '2024',
        date: '12.11.2023',
        price: '700',
    },
    {
        id: 11,
        tags: ['Программирование', 'JavaScript', 'Node.js'],
        name: 'Node.js for Backend Development',
        yearFrom: '2024',
        yearTo: '2025',
        date: '08.12.2024',
        price: '950',
    },
    {
        id: 12,
        tags: ['Программирование', 'PHP'],
        name: 'Web Development with PHP',
        yearFrom: '2025',
        yearTo: '2026',
        date: '22.01.2025',
        price: '890',
    }
];
