export const CoursesCardsData = [
    {
        id: 1,
        title: 'Web Wizardry: Advanced Frontend Development Mastery',
        date: '01.11.2023',
        tags: ['Програмирование', 'JavaScript'],
        value: ["programming", 'javascript'],
        price: '3198',
    },
    {
        id: 2,
        title: 'Delirum Observatie Screening Schaal Screening',
        date: '01.11.2023',
        tags: ['HTML', 'JavaScript', 'Apex Legends'],
        value: ["html", 'javascript', 'apex-legends'],
        price: '3990',
    },
    {
        id: 3,
        title: 'React Revolution: Building Modern User Interfaces',
        date: '01.11.2023',
        tags: ['Програмирование'],
        price: '2690',
    },
    {
        id: 4,
        title: '4-dimensioneel Utrecht Symptoom Dagboek',
        date: '01.11.2023',
        tags: ['Програмирование', 'CSS'],
        price: '4590',
    },
    {
        id: 5,
        title: 'Python Prodigy: Mastering Data Science and Machine Learning',
        date: '01.11.2023',
        tags: ['Програмирование', 'Python', 'Data Science'],
        price: '4990',
    },
    {
        id: 6,
        title: 'UX Unleashed: Designing Intuitive and Engaging User Experiences',
        date: '01.11.2023',
        tags: ['Дизайн', 'UX'],
        price: '3490',
    },
    {
        id: 7,
        title: 'Cybersecurity Fortress: Protecting Digital Assets and Data',
        date: '01.11.2023',
        tags: ['Безопасность', 'Cybersecurity'],
        price: '5290',
    },
    {
        id: 8,
        title: 'Blockchain Beyond Basics: Advanced Cryptocurrency and Smart Contracts',
        date: '01.11.2023',
        tags: ['Програмирование', 'Blockchain'],
        price: '5990',
    },
];